"""Tests for `matching/skills.py` (BRIEF-FR-006 B2).

Covers the acceptance rows in `reports/evidence/FR-006/orders/B2-skills.md`:
B2.3 (proficiency tiers), B2.4 (required/nice-to-have split), and the
building blocks for B2.5/B2.7 (reason text never optimistic about a `basic`
skill, and specific/generated by construction).
"""
from __future__ import annotations

import unittest

from matching import skills as sk


class TestProficiencyTiers(unittest.TestCase):
    def test_ordering_is_explicit_and_visible(self) -> None:
        self.assertEqual(sk.PROFICIENCY_TIERS, ("basic", "foundations", "working", "advanced", "expert"))

    def test_basic_is_partial(self) -> None:
        self.assertTrue(sk.is_partial_proficiency("basic"))
        self.assertFalse(sk.meets_strength_floor("basic"))

    def test_foundations_is_partial(self) -> None:
        self.assertTrue(sk.is_partial_proficiency("foundations"))
        self.assertFalse(sk.meets_strength_floor("foundations"))

    def test_unknown_or_absent_proficiency_is_partial(self) -> None:
        # The whole defect being fixed is optimism: unknown must not default
        # to a strength.
        self.assertTrue(sk.is_partial_proficiency(None))
        self.assertTrue(sk.is_partial_proficiency(""))
        self.assertTrue(sk.is_partial_proficiency("expert-ish"))  # not in the closed vocabulary
        self.assertTrue(sk.is_partial_proficiency("fluent"))  # a plausible-looking but unregistered term
        self.assertIsNone(sk.normalize_proficiency("fluent"))

    def test_working_and_above_can_produce_a_strength(self) -> None:
        for tier in ("working", "advanced", "expert"):
            with self.subTest(tier=tier):
                self.assertFalse(sk.is_partial_proficiency(tier))
                self.assertTrue(sk.meets_strength_floor(tier))

    def test_proficiency_is_case_and_whitespace_insensitive(self) -> None:
        self.assertEqual(sk.normalize_proficiency("  Working  "), "working")
        self.assertEqual(sk.normalize_proficiency("BASIC"), "basic")


class TestRequiredNiceToHaveSplit(unittest.TestCase):
    def test_headed_greenhouse_list_splits_correctly(self) -> None:
        # Modeled on opportunity/fixtures/greenhouse_cloudflare.json's real
        # headed-list shape: <h3>Requirements:</h3><ul><li>...</li></ul>.
        description = (
            "<h2>About the Role</h2>"
            "<p>Cloudflare is looking for a Senior Systems Engineer. "
            "You will work with Rust, Go, and Python across global data centers.</p>"
            "<h3>What you will do:</h3>"
            "<ul><li>Design distributed caching services</li></ul>"
            "<h3>Requirements:</h3>"
            "<ul><li>Proficiency in Rust or Go</li>"
            "<li>Deep understanding of HTTP, TCP, and DNS</li></ul>"
        )
        required, nice_to_have = sk.split_required_and_nice_to_have(
            description, ("Rust", "Go", "Python", "HTTP"),
        )
        self.assertEqual(required, {"rust", "go", "http"})
        # Python is only mentioned in the intro paragraph, before any header.
        self.assertEqual(nice_to_have, {"python"})

    def test_headed_lever_list_splits_correctly(self) -> None:
        # Modeled on opportunity/fixtures/lever_shyftlabs.json's plain-text
        # shape plus a "What you'll bring:" / "Nice to have:" pairing.
        description = (
            "<p>We are looking for a Senior Machine Learning Engineer.</p>"
            "<h3>What you'll bring:</h3>"
            "<ul><li>Strong Python and PyTorch experience</li>"
            "<li>AWS familiarity</li></ul>"
            "<h3>Nice to have:</h3>"
            "<ul><li>Kubernetes exposure</li></ul>"
        )
        required, nice_to_have = sk.split_required_and_nice_to_have(
            description, ("Python", "PyTorch", "AWS", "Kubernetes"),
        )
        self.assertEqual(required, {"python", "pytorch", "aws"})
        self.assertEqual(nice_to_have, {"kubernetes"})

    def test_unheaded_description_yields_all_nice_to_have(self) -> None:
        # opportunity/fixtures/lever_shyftlabs.json's second posting: no
        # headed list at all. Conservative default: nothing is required.
        description = (
            "We are looking for a Senior Machine Learning Engineer to scale our "
            "predictive data pipelines using Python, PyTorch, and AWS. Fully remote worldwide."
        )
        required, nice_to_have = sk.split_required_and_nice_to_have(
            description, ("Python", "PyTorch", "AWS"),
        )
        self.assertEqual(required, frozenset())
        self.assertEqual(nice_to_have, {"python", "pytorch", "aws"})

    def test_no_skills_returns_empty_sets(self) -> None:
        required, nice_to_have = sk.split_required_and_nice_to_have("Requirements: Python", ())
        self.assertEqual(required, frozenset())
        self.assertEqual(nice_to_have, frozenset())


class TestSkillMatchEvaluationAndReason(unittest.TestCase):
    def test_basic_skill_never_produces_a_strength_string(self) -> None:
        # B2.5 anti-regression, at the unit level: search every generated
        # reason string for the old code's exact phrase pattern
        # ("Verified core skill: <Name>") and assert it cannot appear for a
        # skill whose proficiency is `basic`, regardless of required/
        # nice-to-have status.
        founder_skills = {"javascript": ("basic", ("ev-js",))}
        for required in (frozenset({"javascript"}), frozenset()):
            with self.subTest(required=required):
                matches = sk.evaluate_skill_matches(("Javascript",), required, founder_skills)
                self.assertFalse(any(m.is_strength for m in matches))
                reason = sk.render_reason(matches)
                self.assertNotIn("Verified core skill: Javascript", reason)

    def test_required_match_at_working_or_above_is_a_strength(self) -> None:
        founder_skills = {"python": ("working", ("ev-py",)), "sql": ("expert", ("ev-sql-1", "ev-sql-2"))}
        matches = sk.evaluate_skill_matches(
            ("Python", "SQL"), frozenset({"python", "sql"}), founder_skills,
        )
        self.assertTrue(all(m.is_strength for m in matches))

    def test_nice_to_have_match_is_never_a_strength_even_at_expert(self) -> None:
        founder_skills = {"docker": ("expert", ("ev-docker",))}
        matches = sk.evaluate_skill_matches(("Docker",), frozenset(), founder_skills)
        self.assertFalse(matches[0].is_strength)
        self.assertTrue(matches[0].is_partial)

    def test_reason_names_required_list_matched_evidence_and_missing(self) -> None:
        founder_skills = {
            "python": ("expert", ("ev-py-1", "ev-py-2", "ev-py-3")),
            "sql": ("advanced", ("ev-sql-1", "ev-sql-2", "ev-sql-3")),
        }
        matches = sk.evaluate_skill_matches(
            ("Python", "SQL", "Airflow"), frozenset({"python", "sql", "airflow"}), founder_skills,
        )
        reason = sk.render_reason(matches)
        self.assertIn("Required: Python, Sql, Airflow", reason)
        self.assertIn("Python (expert-evidence: 3 record", reason)
        self.assertIn("Sql (advanced, 3 record", reason)
        self.assertIn("Airflow not in your pack", reason)

    def test_five_sample_reasons_each_name_all_four_elements(self) -> None:
        # B2.7: a printed sample of five generated reason strings, each
        # naming the required list, what is matched, the evidence strength,
        # and what is missing.
        scenarios = [
            (("Python", "SQL"), frozenset({"python", "sql"}), {"python": ("expert", ("e1", "e2"))}),
            (("Go", "Rust"), frozenset({"go", "rust"}), {"go": ("working", ("e1",))}),
            (("Docker", "Kubernetes"), frozenset({"docker"}), {"docker": ("basic", ("e1",)), "kubernetes": ("advanced", ("e1",))}),
            (("Terraform",), frozenset({"terraform"}), {}),
            (("AWS", "GCP", "Azure"), frozenset({"aws"}), {"aws": ("advanced", ("e1", "e2")), "gcp": ("working", ("e1",))}),
        ]
        reasons = []
        for opp_skills, required, founder in scenarios:
            matches = sk.evaluate_skill_matches(opp_skills, required, founder)
            reasons.append(sk.render_reason(matches))
        self.assertEqual(len(reasons), 5)
        for reason in reasons:
            self.assertIn("Required:", reason)
            self.assertIn("->", reason)
        print("\nB2.7 sample reason strings:")
        for reason in reasons:
            print(f"  - {reason}")


if __name__ == "__main__":
    unittest.main()
