"""OpportunityOS Opportunity Ingestion & Discovery Pipeline Package."""
from __future__ import annotations

from .adapters import (
    BaseAdapter,
    EUTEDAdapter,
    GreenhouseAdapter,
    HimalayasAdapter,
    LeverAdapter,
    RemoteOKAdapter,
    RemotiveAdapter,
    UNGMAdapter,
    WeWorkRemotelyAdapter,
    WorldBankAdapter,
    get_all_standard_adapters,
)
from .dedupe import DeduplicationResult, deduplicate_opportunities
from .health import SourceHealthMonitor
from .models import (
    Compensation,
    CompensationInterval,
    EmploymentType,
    GeographicEligibility,
    Opportunity,
    OpportunityCluster,
    ProcurementMetadata,
    RemotePolicy,
    SeniorityLevel,
    SourceHealthReport,
    SourceHealthStatus,
    SourceProvenance,
    Track,
)
from .normalization import (
    clean_text,
    derive_geographic_eligibility,
    extract_compensation,
    extract_employment_type,
    extract_remote_policy,
    extract_seniority,
    extract_skills_from_text,
    parse_iso_date,
)
from .pipeline import IngestionBatch, OpportunityPipeline

__all__ = [
    "Track",
    "SeniorityLevel",
    "EmploymentType",
    "RemotePolicy",
    "CompensationInterval",
    "Compensation",
    "ProcurementMetadata",
    "SourceProvenance",
    "GeographicEligibility",
    "Opportunity",
    "OpportunityCluster",
    "SourceHealthStatus",
    "SourceHealthReport",
    "SourceHealthMonitor",
    "DeduplicationResult",
    "deduplicate_opportunities",
    "clean_text",
    "extract_seniority",
    "extract_employment_type",
    "extract_remote_policy",
    "extract_compensation",
    "parse_iso_date",
    "extract_skills_from_text",
    "derive_geographic_eligibility",
    "BaseAdapter",
    "GreenhouseAdapter",
    "LeverAdapter",
    "HimalayasAdapter",
    "RemotiveAdapter",
    "RemoteOKAdapter",
    "WeWorkRemotelyAdapter",
    "UNGMAdapter",
    "WorldBankAdapter",
    "EUTEDAdapter",
    "get_all_standard_adapters",
    "IngestionBatch",
    "OpportunityPipeline",
]

