"""E1.4 -- enumerate docs/SOURCE_REGISTRY.yaml and check policy invariants hold for every
entry, including any board discovered and generated by opportunity/discovery/boards.py."""
from __future__ import annotations

import re
import unittest

from opportunity.registry import DEFAULT_REGISTRY_PATH, SourceRegistry
from recon.sources import ATS_WATCHLIST

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

_KNOWN_WATCHLIST_IDS = {f"{kind}:{token}" for _company, (kind, token) in ATS_WATCHLIST.items()}


def _chunks(text: str) -> list[str]:
    return re.split(r"(?m)^\s*-\s+source_id:\s*", text)[1:]


class RegistryEnumerationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.text = DEFAULT_REGISTRY_PATH.read_text(encoding="utf-8")
        cls.registry = SourceRegistry(DEFAULT_REGISTRY_PATH)
        cls.source_ids = re.findall(r"(?m)^\s*-\s+source_id:\s*(\S+)", cls.text)

    def test_registry_is_nonempty(self) -> None:
        self.assertGreater(len(self.source_ids), 0)

    def test_every_entry_loads_via_the_registry_loader(self) -> None:
        for source_id in self.source_ids:
            with self.subTest(source_id=source_id):
                policy = self.registry.get_policy(source_id)
                self.assertIsNotNone(policy, f"{source_id} did not load")

    def test_zero_entries_have_prepare_or_submit_other_than_disabled(self) -> None:
        # `access.submit` uses a different vocabulary (e.g. "prohibited_or_unknown") and is not
        # the field this check cares about -- scope strictly to the `automation:` block.
        automation_block_re = re.compile(
            r"(?ms)^\s*automation:\s*\n\s*read:\s*\S+\s*\n\s*prepare:\s*(\S+)\s*\n\s*submit:\s*(\S+)"
        )
        for chunk in _chunks(self.text):
            source_id = chunk.splitlines()[0].strip()
            with self.subTest(source_id=source_id):
                match = automation_block_re.search(chunk)
                self.assertIsNotNone(match, f"{source_id} missing a parseable automation: block")
                prepare, submit = match.group(1), match.group(2)
                self.assertEqual(prepare, "disabled", f"{source_id} automation.prepare")
                self.assertEqual(submit, "disabled", f"{source_id} automation.submit")

    def test_every_entry_has_policy_status_and_a_dated_review(self) -> None:
        for chunk in _chunks(self.text):
            source_id = chunk.splitlines()[0].strip()
            with self.subTest(source_id=source_id):
                policy_status = re.search(r"(?m)^\s*policy_status:\s*(\S+)", chunk)
                reviewed = re.search(r"(?m)^\s*last_policy_reviewed:\s*(\S+)", chunk)
                self.assertIsNotNone(policy_status, f"{source_id} missing policy_status")
                self.assertIsNotNone(reviewed, f"{source_id} missing last_policy_reviewed")
                self.assertRegex(reviewed.group(1), _DATE_RE, f"{source_id} last_policy_reviewed")

    def test_newly_discovered_boards_are_read_allowed_and_generated_from_template(self) -> None:
        new_ids = [
            sid
            for sid in self.source_ids
            if sid.startswith(("greenhouse:", "lever:")) and sid not in _KNOWN_WATCHLIST_IDS
        ]
        for source_id in new_ids:
            with self.subTest(source_id=source_id):
                self.assertTrue(self.registry.is_read_allowed(source_id))


if __name__ == "__main__":
    unittest.main()
