import { expect, test, type Page } from "@playwright/test"

const FOUNDER_PASSWORD = process.env.E2E_FOUNDER_PASSWORD ?? "founder-mock-pass"

async function login(page: Page) {
  await page.goto("/")
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel("Password").fill(FOUNDER_PASSWORD)
  await page.getByRole("button", { name: "Sign in" }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByTestId("opportunity-count")).toBeVisible()
}

test.describe("FR-008 feed controls", () => {
  test("facets, score/date/sort, URL restore, chips, and saved-query round trip", async ({ page }) => {
    await login(page)
    const unavailableSorts = page.locator("#feed-sort option:disabled")
    await expect(unavailableSorts).toHaveCount(53)
    await expect(unavailableSorts.first()).toContainText("unavailable:")
    await page.getByLabel("Sort").selectOption("fit_asc")
    await page.getByRole("button", { name: "More filters" }).click()

    const drawer = page.getByTestId("feed-query-drawer")
    await expect(drawer).toBeVisible()
    await expect(drawer).toContainText("Counts describe visible opportunities")
    await expect(drawer).toContainText("Tracking state")
    await expect(drawer.getByText("Tracking state").locator("..").getByRole("checkbox")).toBeDisabled()
    const workModes = drawer.getByTestId("feed-facet-work_mode")
    await workModes.locator("summary").click()
    await workModes.getByLabel("Search Work mode options").fill("remote")
    await workModes.getByRole("checkbox").first().check()
    await workModes.getByLabel("Search Work mode options").fill("")
    await workModes.getByRole("checkbox", { name: /hybrid/i }).check()
    const sources = drawer.getByTestId("feed-facet-source_id")
    await sources.locator("summary").click()
    await sources.getByRole("checkbox").first().check()
    await drawer.getByLabel(/Capability fit minimum/i).fill("75")
    await drawer.getByLabel(/Preference maximum/i).fill("60")
    await drawer.getByLabel("Posted from").fill("2026-01-01")
    await drawer.locator('[aria-label="Capability fit quick thresholds"] button').filter({ hasText: "80+" }).click()
    await drawer.getByRole("button", { name: "Apply filters" }).click()

    await expect(page).toHaveURL(/work_mode=/)
    await expect(page).toHaveURL(/min_fit_score=80/)
    await expect(page).toHaveURL(/posted_from=2026-01-01/)
    await expect(page).toHaveURL(/max_preference_score=60/)
    await expect(page).toHaveURL(/sort_by=fit_asc/)
    await expect.poll(() => page.evaluate(() => new URLSearchParams(window.location.search).getAll("work_mode").length)).toBe(2)
    await expect(page).toHaveURL(/source_id=/)
    await expect(page.getByTestId("feed-query-chips")).toContainText("Work mode")

    await page.getByRole("button", { name: "More filters" }).click()
    const savedDrawer = page.getByTestId("feed-query-drawer")
    await savedDrawer.getByLabel("Saved feed view name").fill("Remote and hybrid high-fit since January")
    await savedDrawer.getByRole("button", { name: "Save view" }).click()
    await expect(savedDrawer.getByRole("button", { name: /Remote and hybrid high-fit since January/ })).toBeVisible()
    await savedDrawer.getByRole("button", { name: "Apply filters" }).click()
    await page.getByRole("button", { name: "Remove Work mode: remote" }).click()
    await expect.poll(() => page.evaluate(() => new URLSearchParams(window.location.search).getAll("work_mode").length)).toBe(1)
    await page.getByRole("button", { name: "More filters" }).click()
    const clearDrawer = page.getByTestId("feed-query-drawer")
    await clearDrawer.getByRole("button", { name: "Clear all" }).click()
    await expect(page).not.toHaveURL(/work_mode=/)
    await expect(page).not.toHaveURL(/source_id=/)
    await clearDrawer.getByRole("button", { name: /Remote and hybrid high-fit since January/ }).click()

    await expect(page).toHaveURL(/work_mode=/)
    await expect(page).toHaveURL(/min_fit_score=80/)
    await expect(page).toHaveURL(/max_preference_score=60/)
    await expect(page).toHaveURL(/sort_by=fit_asc/)
    await page.goBack()
    await expect(page).not.toHaveURL(/work_mode=/)
    await page.goForward()
    await expect(page).toHaveURL(/work_mode=/)
    await page.reload()
    await expect(page).toHaveURL(/work_mode=/)
    await expect(page).toHaveURL(/max_preference_score=60/)
    await expect(page.getByTestId("feed-query-chips")).toContainText("Work mode")
  })
})
