import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendor-generated by `npx msw init` — not authored code, ships its
    // own (already-correct) eslint-disable comments for its own toolchain.
    "public/mockServiceWorker.js",
    // Playwright's own generated output. Both are gitignored, but ESLint has
    // its own ignore list, so without these two entries `npm run lint` is
    // order-dependent: clean on a fresh checkout, and 514 errors / 5548
    // warnings once anyone has run `npx playwright test`, all of them inside
    // Playwright's bundled HTML-report viewer (codeMirrorModule, sw.bundle,
    // defaultSettingsView). CI happens to lint before it runs Playwright, so
    // it never saw this.
    "playwright-report/**",
    "playwright-report-real/**",
    "test-results/**",
    // Cloudflare / OpenNext build output
    ".open-next/**",
    ".wrangler/**",
    "dist/**",
  ]),
]);

export default eslintConfig;
